- name: Install MySQL server
  apt:
    name:
      - mysql-server
      - mysql-client
    update_cache: true

- name: Change root password (fail is not a problem)
  mysql_user:
    name: root
    password: "{{ mysql_root_password}}"
  ignore_errors: yes
