- name: Add repository for PHP
  apt_repository: repo='ppa:ondrej/php'

- name: install php7
  apt:
    name:
      - php7.2
      - php7.2-cgi
      - php7.2-fpm
      - php7.2-memcache
      - php7.2-memcached
      - php7.2-mysql
      - php7.2-gd
      - php7.2-curl
      - php7.2-xmlrpc